const simpleIcon = (slug) => `https://cdn.simpleicons.org/${slug}`;
const simpleIconFile = (slug) =>
  `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${slug}.svg`;

export const techStackItems = [
  { name: 'HTML5', proficiency: 90, isMain: false, icon: 'HTML', iconUrl: simpleIcon('html5') },
  { name: 'CSS3', proficiency: 90, isMain: false, icon: 'CSS', iconUrl: simpleIcon('css') },
  { name: 'JavaScript', proficiency: 90, isMain: true, icon: 'JS', iconUrl: simpleIcon('javascript') },
  { name: 'TypeScript', proficiency: 80, isMain: true, icon: 'TS', iconUrl: simpleIcon('typescript') },
  { name: 'Next.js', proficiency: 80, isMain: true, icon: 'NX', iconUrl: simpleIcon('nextdotjs') },
  { name: 'React.js', proficiency: 90, isMain: true, icon: 'RE', iconUrl: simpleIcon('react') },
  { name: 'React Native', proficiency: 100, isMain: true, icon: 'RN', iconUrl: simpleIcon('react') },
  { name: 'Flutter', proficiency: 100, isMain: true, icon: 'FL', iconUrl: simpleIcon('flutter') },
  { name: 'Dart', proficiency: 100, isMain: true, icon: 'DA', iconUrl: simpleIcon('dart') },
  { name: 'Redux', proficiency: 80, isMain: false, icon: 'RX', iconUrl: simpleIcon('redux') },
  { name: 'React Query', proficiency: 80, isMain: false, icon: 'RQ', iconUrl: simpleIcon('reactquery') },
  { name: 'React Router', proficiency: 80, isMain: false, icon: 'RR', iconUrl: simpleIcon('reactrouter') },
  { name: 'Styled Components', proficiency: 90, isMain: false, icon: 'SC', iconUrl: simpleIcon('styledcomponents') },
  { name: 'Tailwind CSS', proficiency: 100, isMain: true, icon: 'TW', iconUrl: simpleIcon('tailwindcss') },
  { name: 'Vite', proficiency: 90, isMain: false, icon: 'VT', iconUrl: simpleIcon('vite') },
  { name: 'Node.js', proficiency: 90, isMain: false, icon: 'NO', iconUrl: simpleIcon('nodedotjs') },
  { name: 'Python', proficiency: 90, isMain: true, icon: 'PY', iconUrl: simpleIcon('python') },
  { name: 'C++', proficiency: 90, isMain: false, icon: 'C+', iconUrl: simpleIcon('cplusplus') },
  { name: 'PostgreSQL', proficiency: 80, isMain: false, icon: 'PG', iconUrl: simpleIcon('postgresql') },
  { name: 'MongoDB', proficiency: 90, isMain: false, icon: 'MG', iconUrl: simpleIcon('mongodb') },
  { name: 'PyQt', proficiency: 90, isMain: false, icon: 'PQ', iconUrl: simpleIcon('qt') },
  { name: 'Prisma', proficiency: 80, isMain: false, icon: 'PR', iconUrl: simpleIcon('prisma') },
  { name: 'Supabase', proficiency: 80, isMain: false, icon: 'SB', iconUrl: simpleIcon('supabase') },
  { name: 'Render', proficiency: 70, isMain: false, icon: 'RD', iconUrl: simpleIcon('render') },
  { name: 'Git', proficiency: 80, isMain: false, icon: 'GT', iconUrl: simpleIcon('git') },
  { name: 'GitHub', proficiency: 80, isMain: false, icon: 'GH', iconUrl: simpleIcon('github') },
  { name: 'Azure', proficiency: 80, isMain: false, icon: 'AZ', iconUrl: simpleIconFile('microsoftazure') },
  { name: 'Azure AI Foundry', proficiency: 80, isMain: false, icon: 'AI', iconUrl: simpleIconFile('microsoftazure') },
  { name: 'Codex', proficiency: 80, isMain: false, icon: 'CX', iconUrl: simpleIconFile('openai') },
  { name: 'Figma', proficiency: 80, isMain: false, icon: 'FG', iconUrl: simpleIcon('figma') },
  { name: 'Visual Studio Code', proficiency: 90, isMain: false, icon: 'VS', iconUrl: simpleIconFile('visualstudiocode') },
  { name: 'Slack', proficiency: 90, isMain: false, icon: 'SL', iconUrl: simpleIconFile('slack') },
  { name: 'Photoshop', proficiency: 90, isMain: false, icon: 'PS', iconUrl: simpleIconFile('adobephotoshop') },
];

export const certificateItems = [
  {
    title: {
      ko: '빅데이터분석기사',
      en: 'Big Data Analysis Expert',
      de: 'Big Data Analysis Expert',
    },
    issuer: '한국데이터산업진흥원(KDA)',
    issueDate: '2024.12.20',
    image: './assets/images/certificate/kdata.png',
    url: 'https://www.dataq.or.kr/www/sub/a_07.do',
  },
  {
    title: {
      ko: '데이터분석준전문가 (ADsP)',
      en: 'Advanced Data Analytics Semi-Professional',
      de: 'Advanced Data Analytics Semi-Professional',
    },
    issuer: '한국데이터산업진흥원(KDA)',
    issueDate: '2023.09.15',
    image: './assets/images/certificate/kdata.png',
    url: 'https://www.dataq.or.kr/www/sub/a_06.do',
  },
  {
    title: {
      ko: '데이터아키텍처준전문가 (DAsP)',
      en: 'Data Architecture Semi-Professional',
      de: 'Data Architecture Semi-Professional',
    },
    issuer: '한국데이터산업진흥원(KDA)',
    issueDate: '2024.11.29',
    image: './assets/images/certificate/kdata.png',
    url: 'https://www.dataq.or.kr/www/sub/a_05.do',
  },
  {
    title: {
      ko: 'GTQ그래픽기술자격 1급',
      en: 'Graphic Technology Qualification Level-1',
      de: 'Graphic Technology Qualification Level-1',
    },
    issuer: '한국생산성본부(KPC)',
    issueDate: '2023.09.15',
    image: './assets/images/certificate/gtq-level1.png',
    url: 'https://license.kpc.or.kr/nasec/qlfint/qlfint/selectGtqinfomg.do',
  },
  {
    title: {
      ko: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
      en: 'Microsoft Certified: Azure Fundamentals',
      de: 'Microsoft Certified: Azure Fundamentals',
    },
    issuer: 'Microsoft',
    issueDate: '2023.09.02',
    image: './assets/images/certificate/az-900.png',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/?practice-assessment-type=certification',
  },
  {
    title: {
      ko: 'Microsoft Certified: Azure Data Fundamentals (DP-900)',
      en: 'Microsoft Certified: Azure Data Fundamentals',
      de: 'Microsoft Certified: Azure Data Fundamentals',
    },
    issuer: 'Microsoft',
    issueDate: '2023.08.12',
    image: './assets/images/certificate/dp-900.png',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-data-fundamentals/?practice-assessment-type=certification',
  },
  {
    title: {
      ko: 'Microsoft Certified: Azure AI Fundamentals (AI-900)',
      en: 'Microsoft Certified: Azure AI Fundamentals',
      de: 'Microsoft Certified: Azure AI Fundamentals',
    },
    issuer: 'Microsoft',
    issueDate: '2023.07.24',
    image: './assets/images/certificate/ai-900.png',
    url: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/?practice-assessment-type=certification',
  },
  {
    title: {
      ko: 'SQL개발자',
      en: 'Structured Query Language Developer',
      de: 'Structured Query Language Developer',
    },
    issuer: '한국데이터산업진흥원(KDA)',
    issueDate: '2023.04.14',
    image: './assets/images/certificate/kdata.png',
    url: 'https://www.dataq.or.kr/www/sub/a_04.do',
  },
  {
    title: {
      ko: '정보처리기사',
      en: 'Engineer Information Processing',
      de: 'Engineer Information Processing',
    },
    issuer: '한국산업인력공단(HRDK)',
    issueDate: '2022.06.17',
    image: './assets/images/certificate/hrdk.png',
    url: 'https://www.q-net.or.kr/crf005.do?id=crf00503&jmCd=1320',
  },
  {
    title: {
      ko: '리눅스마스터 1급',
      en: 'Linux Master Level-I',
      de: 'Linux Master Level-I',
    },
    issuer: '한국정보통신진흥협회(KAIT)',
    issueDate: '2022.06.10',
    image: './assets/images/certificate/kait.png',
    url: 'https://www.ihd.or.kr/introducesubject1.do',
  },
  {
    title: {
      ko: '컴퓨터활용능력 1급',
      en: 'Computer Specialist in Spreadsheet & Database Level-I',
      de: 'Computer Specialist in Spreadsheet & Database Level-I',
    },
    issuer: '대한상공회의소 자격평가사업단(KCCI)',
    issueDate: '2022.01.08',
    image: './assets/images/certificate/kcci.png',
    url: 'https://license.korcham.net/co/examguide.do?mm=21&cd=0103',
  },
  {
    title: {
      ko: '네트워크관리사 2급',
      en: 'Network Advisor Level-II',
      de: 'Network Advisor Level-II',
    },
    issuer: '한국정보통신자격협회(ICQA)',
    issueDate: '2021.06.13',
    image: './assets/images/certificate/icqa.png',
    url: 'https://www.icqa.or.kr/cn/page/network',
  },
  {
    title: {
      ko: '워드프로세서',
      en: 'Word Processor Specialist',
      de: 'Word Processor Specialist',
    },
    issuer: '대한상공회의소 자격평가사업단(KCCI)',
    issueDate: '2021.06.04',
    image: './assets/images/certificate/kcci.png',
    url: 'https://license.korcham.net/co/examguide.do?mm=22&cd=0102',
  },
  {
    title: {
      ko: '자동차운전면허 (1종보통/1종대형)',
      en: "Driver's License (Class 1 Regular/Heavy Vehicle)",
      de: "Driver's License (Class 1 Regular/Heavy Vehicle)",
    },
    issuer: '한국도로교통공단(KoROAD)',
    issueDate: '2020.02.13',
    image: './assets/images/certificate/koroad.png',
    url: 'https://www.safedriving.or.kr/guide/rerGuide07View.do?menuCode=MN-PO-1117',
  },
  {
    title: {
      ko: 'TOEIC (880/990)',
      en: 'Test Of English for International Communication',
      de: 'Test Of English for International Communication',
    },
    issuer: 'YBM ETS',
    issueDate: '2017.07.17',
    image: './assets/images/certificate/toeic.png',
    url: 'https://exam.toeic.co.kr/common/template/viewContents.php?contentsCode=19',
  },
];

export const courseItems = [
  {
    title: {
      ko: 'CEFR 기준 종합 독일어 강의 (A1)',
      en: 'CEFR-Based Comprehensive German Language Course (A1)',
      de: 'CEFR-basierter umfassender Deutschkurs (A1)',
    },
    provider: '독독독 독일어 어학원(DOK Sprachschule)',
    period: '2024.08.09 - 2024.12.01',
    completedDate: '2024.12.01',
    description: {
      ko: '약 4개월 동안 CEFR A1 수준의 독일어 온라인 강의를 듣고 말하기, 듣기, 쓰기, 읽기를 연습했습니다.',
      en: 'Completed a 4-month online German course based on CEFR standards covering speaking, listening, writing, and reading.',
      de: 'Absolvierte einen viermonatigen Online-Deutschkurs nach CEFR-Standard mit Fokus auf Sprechen, Hören, Schreiben und Lesen.',
    },
    url: 'https://dasdeutsch.com/selbstlernen/',
  },
  {
    title: {
      ko: 'Complete React, Next.js & TypeScript Projects Course 2024',
      en: 'Complete React, Next.js & TypeScript Projects Course 2024',
      de: 'Complete React, Next.js & TypeScript Projects Course 2024',
    },
    provider: 'Udemy',
    period: '2024.08.27 - 2024.11.20',
    completedDate: '2024.11.20',
    description: {
      ko: '약 95시간 동안 React.js, Redux, Next.js, TypeScript, Styled Components로 프로젝트 27개를 만들었습니다.',
      en: 'A 95-hour bootcamp covering React.js, Redux, Next.js, TypeScript, and Styled Components through 27 projects.',
      de: 'Ein 95-stündiges Bootcamp zu React.js, Redux, Next.js, TypeScript und Styled Components mit 27 Projekten.',
    },
    url: 'https://www.udemy.com/certificate/UC-56d6d7d9-24a7-49e8-b497-4aa62462da1c/',
  },
  {
    title: {
      ko: 'React - The Complete Guide 2024 (incl. Next.js, Redux)',
      en: 'React - The Complete Guide 2024 (incl. Next.js, Redux)',
      de: 'React - The Complete Guide 2024 (incl. Next.js, Redux)',
    },
    provider: 'Udemy',
    period: '2024.05.01 - 2024.08.25',
    completedDate: '2024.08.25',
    description: {
      ko: '약 69시간 동안 React.js, Redux, Next.js를 배우고 작은 프로젝트를 만들며 실습했습니다.',
      en: 'A 69-hour course focused on React.js, Redux, and Next.js with multiple mini projects.',
      de: 'Ein 69-stündiger Kurs zu React.js, Redux und Next.js mit mehreren Mini-Projekten.',
    },
    url: 'https://www.udemy.com/certificate/UC-58221581-c13c-44c3-99ad-6ce51fe8cb1d/',
  },
  {
    title: {
      ko: 'The Complete 2024 Web Development Bootcamp',
      en: 'The Complete 2024 Web Development Bootcamp',
      de: 'The Complete 2024 Web Development Bootcamp',
    },
    provider: 'Udemy',
    period: '2023.10.24 - 2024.01.15',
    completedDate: '2024.01.15',
    description: {
      ko: '약 62시간 동안 React.js, Node.js 등 프론트엔드와 백엔드 기술을 배우고 작은 프로젝트로 실습했습니다.',
      en: 'A 62-hour bootcamp covering frontend and backend technologies such as React.js and Node.js with mini projects.',
      de: 'Ein 62-stündiges Bootcamp zu Frontend- und Backend-Technologien wie React.js und Node.js mit Mini-Projekten.',
    },
    url: 'https://www.udemy.com/certificate/UC-e16625ee-336e-4b2d-b08b-60965ef6eb78/',
  },
  {
    title: {
      ko: 'React Native - The Practical Guide',
      en: 'React Native - The Practical Guide',
      de: 'React Native - The Practical Guide',
    },
    provider: 'Udemy',
    period: '2025.02.01 - 2026.01.21',
    completedDate: '2026.01.21',
    description: {
      ko: '약 29시간 동안 React Native로 크로스 플랫폼 앱을 만드는 방법과 화면 구성, 상태 관리, 네이티브 기능 연동을 배웠습니다.',
      en: 'A 29-hour course focused on cross-platform mobile app development with React Native, including UI composition, state management, and native integration.',
      de: 'Ein 29-stündiger Kurs zu plattformübergreifender mobiler App-Entwicklung mit React Native, einschließlich UI-Aufbau, State-Management und nativer Integration.',
    },
    url: 'https://www.udemy.com/certificate/UC-a14befd8-96a6-4443-9463-cbbc2b7df18d/',
  },
  {
    title: {
      ko: 'Flutter & Dart - The Complete Guide',
      en: 'Flutter & Dart - The Complete Guide',
      de: 'Flutter & Dart - The Complete Guide',
    },
    provider: 'Udemy',
    period: '2026.01.11 - 2026.03.23',
    completedDate: '2026.03.23',
    description: {
      ko: '약 30시간 동안 Flutter와 Dart로 여러 플랫폼에서 동작하는 앱의 구조를 배웠습니다. 위젯을 이용한 화면 구성, 상태 관리, 앱 실행 과정도 익혔습니다.',
      en: 'A 30-hour course covering Flutter and Dart for multi-platform app structure, widget-based UI design, state management, and application flow.',
      de: 'Ein 30-stündiger Kurs zu Flutter und Dart mit Fokus auf Multi-Plattform-App-Struktur, widgetbasiertes UI-Design, State-Management und App-Ablauf.',
    },
    url: 'https://www.udemy.com/certificate/UC-6807b4fc-3f9a-453d-90c9-9d27291cba17/',
  },
  {
    title: {
      ko: 'Understanding TypeScript',
      en: 'Understanding TypeScript',
      de: 'Understanding TypeScript',
    },
    provider: 'Udemy',
    period: '2026.03.28 - 2026.05.19',
    completedDate: '2026.05.19',
    description: {
      ko: '약 23시간 동안 TypeScript의 기본 문법과 고급 타입, 제네릭, 인터페이스, 클래스, 모듈, 컴파일 설정을 배웠습니다. React와 Node.js 프로젝트에 타입을 적용하는 방법도 익혔습니다.',
      en: 'A 23-hour course covering TypeScript fundamentals, advanced types, generics, interfaces, classes, modules, and compiler configuration while applying type-safe JavaScript development with React and Node.js.',
      de: 'Ein 23-stündiger Kurs zu TypeScript-Grundlagen, erweiterten Typen, Generics, Interfaces, Klassen, Modulen und Compiler-Konfiguration mit Anwendung in typsicherer JavaScript-Entwicklung mit React und Node.js.',
    },
    url: 'https://www.udemy.com/certificate/UC-47623936-7215-46c3-8a35-7561e7fc08ec/',
  },
  {
    title: {
      ko: 'Flutter Dart | Flutter App Development Projects Course',
      en: 'Flutter Dart | Flutter App Development Projects Course',
      de: 'Flutter Dart | Flutter App Development Projects Course',
    },
    provider: 'Udemy',
    period: '2026.05.23 - 2026.06.14',
    completedDate: '2026.06.14',
    description: {
      ko: '약 18시간 동안 Flutter와 Dart로 웹·모바일 앱을 만드는 방법을 배웠습니다. 프로젝트 구조, 위젯을 이용한 화면 구성, Firebase 연동, 애니메이션, Provider·BLoC·GetX를 이용한 상태 관리를 익혔습니다.',
      en: 'An approximately 18-hour Udemy course covering Flutter and Dart app development, including project structure, widget-based UI, Firebase integration, animations, Provider/BLoC/GetX state management, and web/mobile app workflows.',
      de: 'Ein etwa 18-stundiger Udemy-Kurs zur App-Entwicklung mit Flutter und Dart, einschliesslich Projektstruktur, widgetbasierter UI, Firebase-Integration, Animationen, Provider/BLoC/GetX-State-Management und Web-/Mobile-App-Workflows.',
    },
    url: 'https://www.udemy.com/certificate/UC-4b1f4a4a-8d9b-4969-961f-34445a030127/',
  },
  {
    title: {
      ko: 'The Complete Flutter Development Bootcamp with Dart',
      en: 'The Complete Flutter Development Bootcamp with Dart',
      de: 'The Complete Flutter Development Bootcamp with Dart',
    },
    provider: 'Udemy',
    period: '2026.06.18 - 2026.09.06',
    completedDate: '2026.09.06',
    description: {
      ko: '약 29시간 동안 Dart 문법·객체지향 프로그래밍·비동기 처리와 Flutter 위젯, Provider 상태 관리, 애니메이션, API·Firebase 연동, 사용자 인증을 배웠습니다.',
      en: 'An approximately 29-hour course covering Dart syntax, OOP, and asynchronous programming, plus Flutter widget-based UI, Provider state management, animations, API and Firebase integration, and user authentication.',
      de: 'Ein etwa 29-stündiger Kurs zu Dart-Syntax, OOP und asynchroner Programmierung sowie Flutter-Widget-UIs, Zustandsverwaltung mit Provider, Animationen, API- und Firebase-Integration und Benutzerauthentifizierung.',
    },
    url: 'https://www.udemy.com/certificate/UC-82cc2b98-dc61-47af-b4a8-b35bb1ead955/',
  },
  {
    title: {
      ko: 'Microsoft AI School',
      en: 'Microsoft AI School',
      de: 'Microsoft AI School',
    },
    provider: 'Microsoft Korea',
    period: '2023.04.03 - 2023.09.19',
    completedDate: '2023.09.19',
    description: {
      ko: 'AI와 데이터 관련 기술을 배우고 프로젝트에 적용했습니다.',
      en: 'A training program focused on AI, digital, and data projects to build practical skills and AI foundations.',
      de: 'Ein Trainingsprogramm zu AI, Digital und Data, das praktische Erfahrung und Grundlagen in künstlicher Intelligenz vermittelte.',
    },
    url: 'https://github.com/starrykss/BootCamp_MSAISchool2nd',
  },
  {
    title: {
      ko: '인공지능을 활용한 챗봇 구축 기획/설계/구현',
      en: 'Planning, Designing, and Implementing a Chatbot Using Artificial Intelligence',
      de: 'Planung, Design und Umsetzung eines Chatbots mit künstlicher Intelligenz',
    },
    provider: 'Comento',
    period: '2022.05.08 - 2022.06.05',
    completedDate: '2022.06.05',
    description: {
      ko: '약 5주 동안 현업 개발자의 멘토링을 받으며 Google Dialogflow로 챗봇을 기획하고 설계·구현했습니다.',
      en: 'A 5-week training focused on planning, designing, and building a chatbot service with Google Dialogflow.',
      de: 'Ein 5-wöchiger Kurs zur Planung, Gestaltung und Umsetzung eines Chatbot-Services mit Google Dialogflow.',
    },
    url: 'https://github.com/starrykss/Dialogflow_CondoReservationChatbotProgram',
  },
  {
    title: {
      ko: 'Python(PY4E) 코칭 스터디',
      en: 'Python Coaching Study',
      de: 'Python Coaching Study',
    },
    provider: 'Naver Boost Foundation',
    period: '2021.07.15 - 2021.09.01',
    completedDate: '2021.09.01',
    description: {
      ko: '네이버 부스트코스에서 Python for Everyone 강의와 현업 개발자의 실시간 강의를 듣고, 코치의 피드백을 받으며 팀 과제를 수행했습니다.',
      en: 'An on-tact bootcamp by Naver Boostcourse combining Python for Everyone lectures, team missions, coaching feedback, and live developer sessions.',
      de: 'Ein Online-Bootcamp von Naver Boostcourse mit Python-for-Everyone-Lektionen, Team-Missionen, Coach-Feedback und Live-Sessions von Entwicklern.',
    },
    url: 'https://www.boostcourse.org/study-py4e-1st/intro',
  },
];
